# Generated by Django 5.1.1 on 2025-05-12 11:04

import ckeditor_uploader.fields
import datetime
import django.db.models.deletion
import django.utils.timezone
import funcs
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Author_name', models.CharField(max_length=30, verbose_name='نویسنده')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'نویسنده',
                'verbose_name_plural': '  نویسنده ها',
            },
        ),
        migrations.CreateModel(
            name='Group_blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100, verbose_name='گروه ')),
                ('is_active', models.BooleanField(max_length=False, verbose_name='وضعیت')),
                ('slug', models.CharField(blank=True, max_length=100, null=True, verbose_name='اسلاگ')),
                ('register_data', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ')),
            ],
            options={
                'verbose_name': ' گروه مقاله',
                'verbose_name_plural': 'گروه های مقاله',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_blog', models.CharField(max_length=100, verbose_name='نام گروه')),
                ('subject', models.CharField(max_length=30, verbose_name='موضوع')),
                ('image_name', models.ImageField(default='', upload_to=funcs.FileUpload.upload_to, verbose_name='عکس اصلی')),
                ('view', models.IntegerField(verbose_name='ویو')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('time_read', models.CharField(max_length=30, verbose_name='تایم مطالعه')),
                ('register_data', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ')),
                ('update_data', models.DateTimeField(auto_now_add=True, verbose_name='اپدیت شده')),
                ('description', models.TextField(blank=True, verbose_name='1توضیحات')),
                ('description2', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='2توضیحات')),
                ('key_words', models.CharField(blank=True, max_length=1000, null=True, verbose_name='کلمات کلیدی')),
                ('slug', models.CharField(max_length=40, verbose_name='اسلاگ')),
                ('city_link', models.TextField(blank=True, null=True, verbose_name='لینک شهر')),
                ('Auther_blog', models.ManyToManyField(blank=True, null=True, to='mag.author', verbose_name='نویسنده مقاله')),
                ('grop_blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_of_blog', to='mag.group_blog', verbose_name='گروه مقاله')),
            ],
            options={
                'verbose_name': 'مقاله',
                'verbose_name_plural': 'مقالات',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='اسم کامل')),
                ('email', models.CharField(blank=True, max_length=100, null=True, verbose_name='ایمیل')),
                ('text', models.TextField(verbose_name='پیام')),
                ('is_active', models.BooleanField(default=False)),
                ('register_data', models.DateTimeField(default=datetime.datetime(2025, 5, 12, 11, 4, 4, 425707, tzinfo=datetime.timezone.utc), verbose_name='تاریخ')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_blog', to='mag.blog', verbose_name='مقالات')),
            ],
            options={
                'verbose_name': 'کامنت',
                'verbose_name_plural': 'کامنت ها',
            },
        ),
        migrations.CreateModel(
            name='faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=300, null=True, verbose_name='سوال')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='جواب')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت')),
                ('register_date', models.DateTimeField(blank=True, default=datetime.datetime(2025, 5, 12, 11, 4, 4, 425707, tzinfo=datetime.timezone.utc), null=True, verbose_name='تاریخ ثبت ')),
                ('blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_faqs', to='mag.blog', verbose_name='وبلاگ')),
            ],
            options={
                'verbose_name': 'سوالات متداول',
                'verbose_name_plural': 'سوالات',
            },
        ),
        migrations.CreateModel(
            name='Lable_blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='برچسب')),
                ('link', models.TextField(verbose_name='لینک')),
                ('blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_lable', to='mag.blog', verbose_name='مقالات')),
            ],
        ),
        migrations.CreateModel(
            name='Meta_tag_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, max_length=255, null=True)),
                ('page_title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('og_title', models.CharField(blank=True, max_length=255, null=True)),
                ('og_description', models.TextField(blank=True, null=True)),
                ('alt', models.CharField(blank=True, max_length=100, null=True)),
                ('og_image', models.URLField(blank=True, null=True)),
                ('og_url', models.URLField(blank=True, null=True)),
                ('og_type', models.CharField(blank=True, max_length=50, null=True)),
                ('index', models.BooleanField(default=True, verbose_name='ایندکس')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mag.blog', verbose_name='متا تگ')),
            ],
            options={
                'verbose_name': 'متا تگ های بلاگ',
                'verbose_name_plural': 'متا تگ های وبلاگ',
            },
        ),
        migrations.CreateModel(
            name='Meta_tag_model_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, max_length=255, null=True)),
                ('page_title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('og_title', models.CharField(blank=True, max_length=255, null=True)),
                ('og_description', models.TextField(blank=True, null=True)),
                ('alt', models.CharField(blank=True, max_length=100, null=True)),
                ('og_image', models.URLField(blank=True, null=True)),
                ('og_url', models.URLField(blank=True, null=True)),
                ('og_type', models.CharField(blank=True, max_length=50, null=True)),
                ('index', models.BooleanField(default=True, verbose_name='ایندکس')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mag.group_blog', verbose_name='گروه وبلاگ')),
            ],
        ),
    ]
