# Generated by Django 5.1.1 on 2025-05-12 11:56

import datetime
import funcs
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mag', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image_name',
            field=models.ImageField(default='', upload_to=funcs.FileUpload.upload_to, verbose_name='عکس اصلی'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='register_data',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 12, 11, 56, 0, 150076, tzinfo=datetime.timezone.utc), verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='register_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 5, 12, 11, 56, 0, 150076, tzinfo=datetime.timezone.utc), null=True, verbose_name='تاریخ ثبت '),
        ),
    ]
