# Generated by Django 5.1.1 on 2025-05-14 06:47

import datetime
import funcs
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mag', '0004_alter_blog_image_name_alter_comment_register_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image_name',
            field=models.ImageField(default='', upload_to=funcs.FileUpload.upload_to, verbose_name='عکس اصلی'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='register_data',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 14, 6, 47, 29, 365434, tzinfo=datetime.timezone.utc), verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='register_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 5, 14, 6, 47, 29, 365434, tzinfo=datetime.timezone.utc), null=True, verbose_name='تاریخ ثبت '),
        ),
    ]
