# Generated by Django 5.1.1 on 2025-05-12 08:53

import ckeditor_uploader.fields
import datetime
import django.db.models.deletion
import django.utils.timezone
import funcs
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_group', models.CharField(max_length=100, verbose_name='عنوان گروه')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت')),
                ('update_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ اپدیت')),
                ('slug', models.CharField(blank=True, max_length=100, null=True, verbose_name='نامک')),
            ],
            options={
                'verbose_name': 'گروه خدمات',
                'verbose_name_plural': 'گروه های خدمات',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='موضوع پلن')),
                ('price', models.PositiveIntegerField(blank=True, null=True, verbose_name='قیمت')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت')),
                ('update_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ اپدیت')),
                ('image_name', models.ImageField(blank=True, null=True, upload_to=funcs.FileUpload.upload_to, verbose_name='نام فایل')),
            ],
            options={
                'verbose_name': 'پلن ',
                'verbose_name_plural': 'پلن ها',
            },
        ),
        migrations.CreateModel(
            name='Meta_tag_model_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, max_length=255, null=True)),
                ('page_title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('og_title', models.CharField(blank=True, max_length=255, null=True)),
                ('og_description', models.TextField(blank=True, null=True)),
                ('alt', models.CharField(blank=True, max_length=100, null=True)),
                ('og_image', models.URLField(blank=True, null=True)),
                ('og_url', models.URLField(blank=True, null=True)),
                ('og_type', models.CharField(blank=True, max_length=50, null=True)),
                ('index', models.BooleanField(default=True, verbose_name='ایندکس')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.groups', verbose_name='گروه خدمات')),
            ],
        ),
        migrations.CreateModel(
            name='PlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان')),
                ('is_checked', models.BooleanField(default=True, verbose_name='check')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت')),
                ('update_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ اپدیت')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_item', to='service.plan', verbose_name='پلن')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام سرویس')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='توضیحات')),
                ('text_summery', models.TextField(blank=True, null=True, verbose_name='متن خلاصه')),
                ('image_name', models.ImageField(upload_to=funcs.FileUpload.upload_to, verbose_name='نام فایل')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت')),
                ('update_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ اپدیت')),
                ('slug', models.CharField(blank=True, max_length=100, null=True, verbose_name='نامک')),
                ('city', models.TextField(blank=True, null=True, verbose_name='شهر')),
                ('groups', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.groups', verbose_name='گروه ها')),
            ],
            options={
                'verbose_name': 'سرویس',
                'verbose_name_plural': 'سرویس ها',
            },
        ),
        migrations.AddField(
            model_name='plan',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plan_service', to='service.service', verbose_name='سرویس ها'),
        ),
        migrations.CreateModel(
            name='Meta_tag_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, max_length=255, null=True)),
                ('page_title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('og_title', models.CharField(blank=True, max_length=255, null=True)),
                ('og_description', models.TextField(blank=True, null=True)),
                ('alt', models.CharField(blank=True, max_length=100, null=True)),
                ('og_image', models.URLField(blank=True, null=True)),
                ('og_url', models.URLField(blank=True, null=True)),
                ('og_type', models.CharField(blank=True, max_length=50, null=True)),
                ('index', models.BooleanField(default=True, verbose_name='ایندکس')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.service', verbose_name='خدمات')),
            ],
            options={
                'verbose_name': 'متا تگ های بلاگ',
                'verbose_name_plural': 'متا تگ های وبلاگ',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='موضوع')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت')),
                ('update_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ اپدیت')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_services', to='service.service', verbose_name='سرویس')),
            ],
            options={
                'verbose_name': 'سرویس',
                'verbose_name_plural': 'سرویس ها ایتم',
            },
        ),
        migrations.CreateModel(
            name='GalleryService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alt', models.CharField(blank=True, max_length=100, null=True, verbose_name='متن جایگزین')),
                ('image_name', models.ImageField(upload_to=funcs.FileUpload.upload_to, verbose_name='عکس')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت فعال')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ساخته شده')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_service', to='service.service', verbose_name='عکس ها')),
            ],
            options={
                'verbose_name': 'عکس',
                'verbose_name_plural': 'گالری خدمات',
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='کلمه')),
                ('value', models.CharField(max_length=100, verbose_name='مقدار')),
                ('is_active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serivce_feature', to='service.service', verbose_name='خدمات')),
            ],
        ),
        migrations.CreateModel(
            name='faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, max_length=300, null=True, verbose_name='سوال')),
                ('answer', models.TextField(blank=True, null=True, verbose_name='جواب')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت')),
                ('register_date', models.DateTimeField(blank=True, default=datetime.datetime(2025, 5, 12, 8, 53, 5, 247661, tzinfo=datetime.timezone.utc), null=True, verbose_name='تاریخ ثبت ')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services_faqs', to='service.service', verbose_name='وبلاگ')),
            ],
            options={
                'verbose_name': 'سوالات متداول',
                'verbose_name_plural': 'سوالات',
            },
        ),
    ]
