# Generated by Django 5.1.1 on 2025-05-12 09:26

import datetime
import funcs
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='svg_file',
            field=models.TextField(blank=True, null=True, verbose_name='svg '),
        ),
        migrations.AlterField(
            model_name='faq',
            name='register_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 5, 12, 9, 26, 18, 615277, tzinfo=datetime.timezone.utc), null=True, verbose_name='تاریخ ثبت '),
        ),
        migrations.AlterField(
            model_name='galleryservice',
            name='image_name',
            field=models.ImageField(upload_to=funcs.FileUpload.upload_to, verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='image_name',
            field=models.ImageField(blank=True, null=True, upload_to=funcs.FileUpload.upload_to, verbose_name='نام فایل'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image_name',
            field=models.ImageField(upload_to=funcs.FileUpload.upload_to, verbose_name='نام فایل'),
        ),
    ]
