# Generated by Django 5.1.1 on 2025-05-12 06:35

import ckeditor_uploader.fields
import django.utils.timezone
import funcs
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_company', models.CharField(max_length=100, verbose_name='نام شرکت')),
                ('phone_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره موبایل')),
                ('mobile_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='شماره همراه ')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل شرکت')),
                ('image_name', models.FileField(blank=True, null=True, upload_to=funcs.FileUpload.upload_to, validators=[funcs.validate_image_or_svg], verbose_name='اپلود کردن عکس')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت')),
                ('time_work', models.CharField(blank=True, max_length=100, null=True, verbose_name='تایم کاری')),
                ('address', models.TextField(blank=True, null=True, verbose_name='ادرس شرکت')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='ساخته شده')),
                ('update_at', models.DateTimeField(auto_now_add=True, verbose_name='اپدیت کردن')),
            ],
            options={
                'verbose_name': 'اطلاعات شرکت',
                'verbose_name_plural': 'اطلاعات های شرکت',
            },
        ),
        migrations.CreateModel(
            name='MediaUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_social', models.CharField(max_length=100, verbose_name='نام مجازی')),
                ('link', models.TextField(verbose_name='لینک')),
                ('icon', models.TextField(blank=True, null=True, verbose_name='ایکون')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ساخت')),
            ],
            options={
                'verbose_name': 'شبکه اجتماعی ',
                'verbose_name_plural': 'شبکه اجتماعی های شرکت',
            },
        ),
        migrations.CreateModel(
            name='Meta_tag_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(blank=True, max_length=255, null=True)),
                ('page_title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('og_title', models.CharField(blank=True, max_length=255, null=True)),
                ('og_description', models.TextField(blank=True, null=True)),
                ('alt', models.CharField(blank=True, max_length=100, null=True)),
                ('og_image', models.URLField(blank=True, null=True)),
                ('og_url', models.URLField(blank=True, null=True)),
                ('og_type', models.CharField(blank=True, max_length=50, null=True)),
                ('index', models.BooleanField(default=True, verbose_name='ایندکس')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تگ مدل',
                'verbose_name_plural': 'تگ های متا صفحه اصلی',
            },
        ),
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='موضوع')),
                ('image_name', models.FileField(upload_to=funcs.FileUpload.upload_to, validators=[funcs.validate_image_or_svg], verbose_name='نام تصویر')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='ثبت شده')),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه ها',
            },
        ),
        migrations.CreateModel(
            name='ResumCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='موضوع')),
                ('answer', models.CharField(max_length=20, verbose_name='جواب رزوم')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'رزومه سایت',
                'verbose_name_plural': 'رزومه های سایت',
            },
        ),
        migrations.CreateModel(
            name='Slider_main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان')),
                ('text', models.TextField(blank=True, null=True, verbose_name='متن')),
                ('image_name', models.ImageField(upload_to=funcs.FileUpload.upload_to, verbose_name='نام تصویر')),
                ('alt', models.CharField(blank=True, max_length=100, null=True, verbose_name='متن جایگزین ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('create_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ ثبت')),
            ],
            options={
                'verbose_name': 'عکس',
                'verbose_name_plural': 'عکس های اسلایدر',
            },
        ),
        migrations.CreateModel(
            name='text_description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.FileField(blank=True, null=True, upload_to=funcs.FileUpload.upload_to, validators=[funcs.validate_image_or_svg], verbose_name='نام تصویر')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='توضیحات')),
            ],
        ),
        migrations.CreateModel(
            name='WhyUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.FileField(upload_to=funcs.FileUpload.upload_to, validators=[funcs.validate_image_or_svg], verbose_name='نام تصویر')),
                ('title', models.CharField(max_length=100, verbose_name='متن')),
                ('text', models.TextField(verbose_name='متن')),
                ('is_active', models.BooleanField(default=True, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'چرا ما',
                'verbose_name_plural': 'چرا ما ؟ ',
            },
        ),
    ]
