# Generated by Django 5.1.1 on 2025-05-12 08:53

import funcs
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='image_name',
            field=models.FileField(blank=True, null=True, upload_to=funcs.FileUpload.upload_to, validators=[funcs.validate_image_or_svg], verbose_name='اپلود کردن عکس'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='image_name',
            field=models.FileField(upload_to=funcs.FileUpload.upload_to, validators=[funcs.validate_image_or_svg], verbose_name='نام تصویر'),
        ),
        migrations.AlterField(
            model_name='slider_main',
            name='image_name',
            field=models.ImageField(upload_to=funcs.FileUpload.upload_to, verbose_name='نام تصویر'),
        ),
        migrations.AlterField(
            model_name='text_description',
            name='image_name',
            field=models.FileField(blank=True, null=True, upload_to=funcs.FileUpload.upload_to, validators=[funcs.validate_image_or_svg], verbose_name='نام تصویر'),
        ),
        migrations.AlterField(
            model_name='whyus',
            name='image_name',
            field=models.FileField(upload_to=funcs.FileUpload.upload_to, validators=[funcs.validate_image_or_svg], verbose_name='نام تصویر'),
        ),
    ]
