# Generated by Django 5.1.1 on 2025-05-12 11:56

import ckeditor_uploader.fields
import funcs
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_company_image_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='text_description2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.FileField(blank=True, null=True, upload_to=funcs.FileUpload.upload_to, validators=[funcs.validate_image_or_svg], verbose_name='نام تصویر')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='توضیحات')),
                ('title', models.CharField(blank=True, max_length=40, null=True, verbose_name='عنوان توضیحات')),
            ],
            options={
                'verbose_name': 'متن پایین',
                'verbose_name_plural': 'متن پایین تصویر',
            },
        ),
        migrations.AlterField(
            model_name='company',
            name='image_name',
            field=models.FileField(blank=True, null=True, upload_to=funcs.FileUpload.upload_to, validators=[funcs.validate_image_or_svg], verbose_name='اپلود کردن عکس'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='image_name',
            field=models.FileField(upload_to=funcs.FileUpload.upload_to, validators=[funcs.validate_image_or_svg], verbose_name='نام تصویر'),
        ),
        migrations.AlterField(
            model_name='slider_main',
            name='image_name',
            field=models.ImageField(upload_to=funcs.FileUpload.upload_to, verbose_name='نام تصویر'),
        ),
        migrations.AlterField(
            model_name='text_description',
            name='image_name',
            field=models.FileField(blank=True, null=True, upload_to=funcs.FileUpload.upload_to, validators=[funcs.validate_image_or_svg], verbose_name='نام تصویر'),
        ),
        migrations.AlterField(
            model_name='whyus',
            name='image_name',
            field=models.FileField(upload_to=funcs.FileUpload.upload_to, validators=[funcs.validate_image_or_svg], verbose_name='نام تصویر'),
        ),
    ]
