# Generated by Django 5.1.1 on 2025-05-13 05:08

import funcs
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_text_description2_alter_company_image_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=100, verbose_name='نام کامل')),
                ('semat', models.CharField(max_length=100, verbose_name='سمت')),
                ('text', models.TextField(verbose_name='متن پیام')),
                ('isAvtive', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='company',
            name='image_name',
            field=models.FileField(blank=True, null=True, upload_to=funcs.FileUpload.upload_to, validators=[funcs.validate_image_or_svg], verbose_name='اپلود کردن عکس'),
        ),
        migrations.AlterField(
            model_name='projectmodel',
            name='image_name',
            field=models.FileField(upload_to=funcs.FileUpload.upload_to, validators=[funcs.validate_image_or_svg], verbose_name='نام تصویر'),
        ),
        migrations.AlterField(
            model_name='slider_main',
            name='image_name',
            field=models.ImageField(upload_to=funcs.FileUpload.upload_to, verbose_name='نام تصویر'),
        ),
        migrations.AlterField(
            model_name='text_description',
            name='image_name',
            field=models.FileField(blank=True, null=True, upload_to=funcs.FileUpload.upload_to, validators=[funcs.validate_image_or_svg], verbose_name='نام تصویر'),
        ),
        migrations.AlterField(
            model_name='text_description2',
            name='image_name',
            field=models.FileField(blank=True, null=True, upload_to=funcs.FileUpload.upload_to, validators=[funcs.validate_image_or_svg], verbose_name='نام تصویر'),
        ),
        migrations.AlterField(
            model_name='whyus',
            name='image_name',
            field=models.FileField(upload_to=funcs.FileUpload.upload_to, validators=[funcs.validate_image_or_svg], verbose_name='نام تصویر'),
        ),
    ]
